const { commitLint } = require('@kkkaoru/git-hooks');
const { findPackageNames } = require('@kkkaoru/git-hooks');

module.exports = {
  ...commitLint,
  rules: {
    'scope-enum': [
      2,
      'always',
      // generated by this command
      // npm ls --json | jq -r '.dependencies | keys[] | select(startswith("@"))' | awk -F'/' '{printf("\'%s\',\n", $2)}' | pbcopy
      findPackageNames(),
    ],
  },
};
